# Corrected EKS Cluster Manifest for a PROD environment
# This version uses subnets in supported Availability Zones.
# Use with: eksctl create cluster -f <filename.yaml>

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: razos-eks-cluster-prod
  region: us-east-1
  version: "1.30"

# This section defines the VPC and Subnets that eksctl will use
vpc:
  id: "vpc-08a02321505b91038" # Your actual VPC ID
  subnets:
    # Subnets for the EKS Control Plane and internet-facing Load Balancers.
    # FIX: These subnets are in supported AZs (us-east-1a, us-east-1b)
    public:
      us-east-1a:
        id: "subnet-08ea974ddd8ab2c72"
      us-east-1b:
        id: "subnet-0df20f9da1415d533"

    # Subnets where the EC2 worker nodes will be placed.
    # FIX: These subnets are in supported AZs (us-east-1c, us-east-1d)
    private:
      us-east-1c:
        id: "subnet-0f0bd22bc22e33368"
      us-east-1d:
        id: "subnet-0aba78c4b07d9d549"

# This section defines the group of EC2 instances that will be your worker nodes
managedNodeGroups:
  - name: prod-general-workers
    instanceType: t3.medium
    desiredCapacity: 3
    volumeSize: 80
    privateNetworking: true
    labels:
      role: general-prod